frontend:
  directory: "/opt/kubeseal-ui/frontend"
server:
  port: "3000"
  dynamicProjectDiscovery:
    enabled: false
    period: 15m
  projects: [ ]
#    - name: "sealed-secrets"
#      controllerName: "sealed-secrets"
#      controllerNamespace: "sealed-secrets"
