frontend:
  directory: ".dist/frontend"
server:
  port: "3000"
  dynamicProjectDiscovery:
    enabled: true
    period: 15m
  projects: [ ]
#    - name: "sealed-secrets"
#      controllerName: "sealed-secrets"
#      controllerNamespace: "sealed-secrets"
