apiVersion: v1
kind: Secret
metadata:
  name: clusterConfig
  namespace: default
  labels:
    kubeseal-ui/cluster-name: cluster
    kubeseal-ui/secret-type: cluster
type: Opaque
stringData:
  config: |
    apiVersion: v1
    kind: Config
    current-context: kubeseal-ui
    preferences: { }
    clusters:
      - cluster:
          certificate-authority-data: <ca-data>
          server: <api-server-address>
        name: kubeseal-ui
    contexts:
      - context:
          cluster: kubeseal-ui
          user: kubeseal-ui
        name: kubeseal-ui
    users:
      - name: kubeseal-ui
        user:
          token: <token-data>
