apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeseal-ui
  namespace: kubeseal-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeseal-ui-namespace-reader
subjects:
  - kind: ServiceAccount
    name: kubeseal-ui
    namespace: kubeseal-ui
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: ""
