apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeseal-ui-config
data:
  config.yaml: |
    frontend:
      directory: "/opt/kubeseal-ui/frontend"
    server:
      port: {{- toYaml .Values.config.port }}
      dynamicProjectDiscovery:
        enabled: {{ .Values.config.dynamicProjectDiscovery.enabled }}
        period: {{ .Values.config.dynamicProjectDiscovery.period }}
      {{- if .Values.config.staticProjectConfiguration.enabled }}
      {{- if .Values.config.projects }}
      projects:
        {{- toYaml .Values.config.projects | nindent 8 }}
      {{ else }}
      {{- if eq .Values.config.dynamicProjectDiscovery.enabled false }}
      projects:
        - name: "sealed-secrets"
          controllerName: "sealed-secrets"
          controllerNamespace: "sealed-secrets"
      {{ else }}
      projects: [ ]
      {{ end }}
      {{ end }}
      {{ else }}
      projects: [ ]
      {{ end }}
