apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
  namespace: kubeseal-ui
  labels:
    kubeseal-ui/cluster-name: <cluster-name>
    kubeseal-ui/secret-type: cluster
type: Opaque
stringData:
  config: |
    apiVersion: v1
    kind: Config
    current-context: kubeseal-ui
    preferences: { }
    clusters:
      - cluster:
          certificate-authority-data: <ca-data>
          server: <api-server-url>
        name: kubeseal-ui
    contexts:
      - context:
          cluster: kubeseal-ui
          user: kubeseal-ui
        name: kubeseal-ui
    users:
      - name: kubeseal-ui
        user:
          token: <service-account-token>
