apiVersion: v1
kind: Namespace
metadata:
  name: "kubeseal-ui"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "sealed-secrets"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "ns-c"
  labels:
    kubeseal-ui: "sealed-secrets"
  annotations:
    kubeseal-ui/projectName: "Application C"
    kubeseal-ui/controllerName: "sealed-secrets"
    kubeseal-ui/controllerNamespace: "sealed-secrets"
---
apiVersion: v1
kind: Namespace
metadata:
  name: "ns-d"
  labels:
    kubeseal-ui: "sealed-secrets"
  annotations:
    kubeseal-ui/projectName: "Application D"
    kubeseal-ui/controllerName: "sealed-secrets"
    kubeseal-ui/controllerNamespace: "sealed-secrets"
