name: release helm charts

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  rerlease-helm-charts:
    name: Charts
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "{{ .Version }}"
          CR_PAGES_INDEX_PATH: "charts/index.yaml"